language: android
jdk: oraclejdk8

env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-25
    - android-24
    - android-23
    - android-22
    - android-21
    - android-20
    - android-19
    - android-18
    - android-17
    - android-16
    - android-15
    - android-14
    - android-13
    - android-12
    - android-11
    - android-10
    - android-9

before_script:
  - chmod +x gradlew